# Build custom CI image: http://docs.shippable.com/ci/tutorial/build-custom-ci-image/

resources:
  # Repository with recipe for CI image creation
  - name: parpe_ci_image_recipe_repo
    type: gitRepo
    integration: integration_github
    pointer:
      sourceName: "ICB-DCM/custom_ci_image"
      branch: master

  # CI image on dockerhub
  - name: parpe_dockerhub_ci_image
    type: image
    integration: integration_docker_hub
    versionTemplate:
      sourceName: "dweindl/parpeci"
      versionName: latest

jobs:
  # How to build our custom CI image
  - name: parpe_build_custom_image_job
    type: runSh
    steps:
      # Input resource: CI image recipe
      - IN: parpe_ci_image_recipe_repo
      - TASK:
          name: parpe_build_custom_image_task
          script:
            - pushd $(shipctl get_resource_state "parpe_ci_image_recipe_repo")
            # Extract image information and Docker registry credentials from resources using shipctl utility
            # Detailed shipctl guide is at http://docs.shippable.com/platform/tutorial/workflow/using-shipctl/
            - export IMG_NAME=$(shipctl get_resource_version_key parpe_dockerhub_ci_image "sourceName")
            - export DH_USR_NAME=$(shipctl get_integration_resource_field parpe_dockerhub_ci_image "userName")
            - export DH_PASS=$(shipctl get_integration_resource_field parpe_dockerhub_ci_image "password")
            - export DH_URL=$(shipctl get_integration_resource_field parpe_dockerhub_ci_image "url")
            # Docker commands to build and push to registry
            - sudo docker build -t=$IMG_NAME:$BUILD_NUMBER --pull .
            - sudo docker login -u $DH_USR_NAME -p $DH_PASS
            - sudo docker push $IMG_NAME:$BUILD_NUMBER
            - popd
            - echo "Update OUT resource to create a new version '$BUILD_NUMBER' that will trigger rest of the workflow"
            - shipctl put_resource_state_multi parpe_dockerhub_ci_image "versionName=$BUILD_NUMBER"
      # Output resource: CI Image
      - OUT: parpe_dockerhub_ci_image
    flags:
      # Use flags to filter SPOG views
      - custom_ci_img
      - war
