# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables
name: Test benchmark collection models
on: [push, pull_request, workflow_dispatch]
jobs:
  container:
    runs-on: ubuntu-latest
    container: ghcr.io/icb-dcm/custom_ci_image:master
    name: benchmark models
    steps:
    - uses: actions/checkout@master

    - run: echo "PARPE_BASE=$(pwd)" >> $GITHUB_ENV
    - run: echo "PARPE_BUILD=${PARPE_BASE}/build" >> $GITHUB_ENV
    - run: echo "AMICI_PATH=${PARPE_BASE}/deps/AMICI/" >> $GITHUB_ENV

    # Build dependencies

    - name: Install AMICI deps
      run: |
        cd $AMICI_PATH \
          && scripts/buildSuiteSparse.sh \
          && scripts/buildSundials.sh

    - name: Install AMICI
      run: |
        cmake \
            -S ${AMICI_PATH} \
            -B ${AMICI_PATH}/build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DENABLE_PYTHON=ON \
            -DBUILD_TESTS=OFF \
          && cmake --build "${AMICI_PATH}/build" --parallel -- VERBOSE=1

    - name: Install parPE Python deps
      run: |
        pip install -r ${PARPE_BASE}/python/requirements.txt

    - name: Configure parpe
      run: |
        cmake \
          -S"${PARPE_BASE}" \
          -B"${PARPE_BUILD}" \
          -DIPOPT_INCLUDE_DIRS=/usr/include/coin/ \
          -DIPOPT_LIBRARIES=/usr/lib/libipopt.so \
          -DGCOVR_REPORT=TRUE \
          -DBUILD_TESTING=FALSE

    - name: Build parPE
      run: |
        cmake --build "${PARPE_BUILD}" --parallel -- VERBOSE=1

    # Actual Benchmark model tests

    - name: Benchmark models --- requirements
      run: |
        sudo apt install bc \
          && $PARPE_BASE/misc/run_in_venv.sh $PARPE_BASE/build/venv \
              pip3 install shyaml

    - name: Benchmark models --- repository
      env:
        BM_REPO_URL: https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab.git
      run: |
        cd $PARPE_BASE/benchmark_collection \
          && git clone --depth 1 $BM_REPO_URL

    - name: Benchmark models --- tests
      run: |
        cd $PARPE_BASE/benchmark_collection \
          && AMICI_PARALLEL_COMPILE=4 \
             BENCHMARK_COLLECTION="$(pwd)/Benchmark-Models-PEtab/Benchmark-Models/" \
             $PARPE_BASE/misc/run_in_venv.sh $PARPE_BASE/build/venv ./all.sh
