# https://github.com/marketplace/actions/publish-docker
name: Deploy to dockerhub
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@2.8
      with:
        name: dweindl/parpe
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: container/charliecloud/parpe_base/
        dockerfile: Dockerfile
        tag_names: true
